apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app-net: "true"
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: AUTH_HOST
              value: auth
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: weather
            - name: WEATHER_PORT
              value: "5000"
          image: "{{ .Values.image.ui.repository }}:{{ .Values.image.ui.tag }}"
          name: ui
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
